### ISSUE TITLE
hoursOnRecord wont display 

### ISSUE THREAD

**Issue by foen** [MattRyder/SteamAPI#8]
hi i played dayz for 1160 hours when pulling the info with getgamelist the output is 1 did not look into it but there must be songthing wrong while parsing the data 

fixed for myself by changing in SteamUser.php from float to string 
(float)$game->hoursOnRecord; changed to (string)$game->hoursOnRecord; and it worked for me :)

**Comment by MattRyder** [comment]
Hi, thanks for reporting this. I'm not likely to have the time to repair this before this weekend, so before then I'd like to get a bit of information from you that may expedite my fixing of this issue.

Could I obtain which version of PHP you're using that raised this error, and if possible your SteamID (via here or email would be fine)?

Thanks for using SteamAPI, by the way!

**Comment by foen** [comment]
my steam id is foen1337

**Comment by foen** [comment]
sorry for that mail lol
my steam ID is foen1337
if you check my game dayz and then see the hoursonrecord there should be
something like 1156 but cos ts a floating point in your scipts its not
handled right then it will be 1 cos it got displayed as 1.156
i fixed it for now by changing floating point to string for now

**Comment by MattRyder** [comment]
Hi @foen, just to follow up, the bug has been fixed thanks to your helpful bug report! :+1: 
If you hit any more issues, please send another report over.

You may also be interested to know that I've added wrappings for SteamApps, which allows you to check online servers and the up-to-date status of a Steam game!

**Comment by foen** [comment]
thx Matt i will look into your SteamApps Wrapping iam using this script for
some time now and its really stable.
